arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
  - joint_1
  - joint_2
#   constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      base_link: {trajectory: 0.0, goal: 0.0}
#      first_link: {trajectory: 0.0, goal: 0.0}
#      second_link: {trajectory: 0.0, goal: 0.0}
#    stop_trajectory_duration: 0.5
#    state_publish_rate:  25
#    action_monitor_rate: 10
#/gazebo_ros_control:
#    pid_gains:
#      joint_1: {p: 1000.0, i: 100.0, d: 10.0}
#      joint_2: {p: 1000.0, i: 100.0, d: 10.0}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
