kinematics:
  link_1:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  link_2:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 3.1416
  link_3:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  link_4:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 3.1416
  link_5:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  link_6:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 3.1416
  link_7:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  link_8:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 3.1416
  hash: calib_12788084448423163542